# Generated by Django 5.2.8 on 2025-11-14 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoralTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('cover', models.ImageField(null=True, upload_to='stories/')),
                ('content', models.TextField()),
                ('page_count', models.IntegerField(default=0)),
                ('runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('age_group', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('classic', '명작동화'), ('custom', '제작동화'), ('extended', '확장동화')], default='classic', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.child')),
                ('morals', models.ManyToManyField(blank=True, related_name='stories', to='story.moraltheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.clonedvoice')),
            ],
        ),
        migrations.CreateModel(
            name='StoryExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_content', models.TextField()),
                ('dialogue_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='accounts.child')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='story.story')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Illustrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='illustrations/')),
                ('prompt', models.TextField()),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('story_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='story.storypage')),
            ],
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.child')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='story.story')),
            ],
            options={
                'unique_together': {('story', 'child')},
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
    ]
