# Generated by Django 5.2.7 on 2025-10-15 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_child_profile_image_user_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(null=True, upload_to='stories/')),
                ('content', models.TextField()),
                ('page_count', models.IntegerField(default=0)),
                ('runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('age_group', models.CharField(blank=True, max_length=50, null=True)),
                ('moral', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.voice')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='story.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='story.story')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Illustrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='illustrations/')),
                ('prompt', models.TextField()),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('story_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='story.storypage')),
            ],
        ),
        migrations.CreateModel(
            name='StoryTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='story.story')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='story.theme')),
            ],
            options={
                'unique_together': {('story', 'theme')},
            },
        ),
    ]
