# Generated by Django 5.2.7 on 2025-11-04 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_child_profile_image_user_profile_image_and_more"),
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="accounts.child",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="accounts.voice",
            ),
        ),
    ]
