# Generated by Django 5.2.7 on 2025-11-13 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_voice_profile_image"),
        ("story", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Theme",
            new_name="MoralTheme",
        ),
        migrations.AlterUniqueTogether(
            name="storytheme",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="storytheme",
            name="story",
        ),
        migrations.RemoveField(
            model_name="storytheme",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="story",
            name="moral",
        ),
        migrations.RemoveField(
            model_name="story",
            name="released_at",
        ),
        migrations.RemoveField(
            model_name="story",
            name="status",
        ),
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.CharField(
                choices=[
                    ("classic", "명작동화"),
                    ("custom", "제작동화"),
                    ("extended", "확장동화"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="morals",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="story.moraltheme"
            ),
        ),
        migrations.CreateModel(
            name="StoryExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extended_content", models.TextField()),
                ("dialogue_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="accounts.child",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="story.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="accounts.child",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="story.story",
                    ),
                ),
            ],
            options={
                "unique_together": {("story", "child")},
            },
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="story.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("story", "user")},
            },
        ),
        migrations.DeleteModel(
            name="Extension",
        ),
        migrations.DeleteModel(
            name="StoryTheme",
        ),
    ]
