# Generated by Django 5.2.8 on 2025-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_illustrations_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustrations',
            name='style',
        ),
        migrations.AddField(
            model_name='story',
            name='illustration_style',
            field=models.CharField(blank=True, choices=[('watercolor', '수채화'), ('oil', '유화'), ('crayon', '크레파스'), ('3d', '3D 애니메이션')], max_length=50, null=True),
        ),
    ]
