# Generated by Django 5.2.7 on 2025-11-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_voice_profile_image"),
        ("story", "0002_rename_theme_moraltheme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="accounts.child",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="accounts.voice",
            ),
        ),
    ]
