# Generated by Django 5.2.7 on 2025-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_alter_story_child_alter_story_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.CharField(
                choices=[
                    ("classic", "명작동화"),
                    ("custom", "제작동화"),
                    ("extended", "확장동화"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
