# Generated by Django 5.2.8 on 2025-11-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_remove_illustrations_style_story_illustration_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustrations',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='story.story'),
        ),
        migrations.AddField(
            model_name='illustrations',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='illustrations',
            name='story_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='story.storypage'),
        ),
    ]
