# Generated by Django 5.2.7 on 2025-11-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0003_alter_story_child_alter_story_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="moraltheme",
            name="key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
