# Generated by Django 5.2.8 on 2025-11-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0004_illustrations_story_illustrations_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="illustration_context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
