# Generated by Django 5.2.8 on 2025-11-28 08:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clonedvoice_voice_name'),
        ('story', '0005_story_illustration_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '좋아요'), ('dislike', '아쉬워요')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.child')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='story.story')),
            ],
            options={
                'unique_together': {('story', 'child')},
            },
        ),
    ]
