FROM python:3.10

# ===== System Dependencies =====
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    git \
    curl \
    unzip \
    ffmpeg \
    espeak \
    espeak-ng \
    libopenblas-dev \
    libsndfile1 \
    libsndfile1-dev \
    sox \
    libavcodec-dev \
    libavformat-dev \
    libavdevice-dev \
    libavfilter-dev \
    libavutil-dev \
    libswscale-dev \
    libswresample-dev \
    mecab \
    libmecab-dev \
    mecab-ipadic-utf8 \
    festival \
    festlex-cmu \
    festlex-poslex \
    festvox-kallpc16k \
    libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*

# ===== Workdir =====
WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install "Cython<3.0"

# PyTorch CPU
RUN pip install torch==2.1.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install torchaudio==2.1.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

RUN pip install av==12.0.0
RUN pip install faster-whisper==0.8.0 --no-deps
RUN pip install whisper-timestamped==1.14.1

# ===== Install base requirements =====
RUN pip install -r requirements.txt

# ===== phonemizer & pyopenjtalk 설치 =====
RUN pip install phonemizer pyopenjtalk

RUN pip install librosa==0.10.0.post2 \
    numba \
    audioread \
    scipy \
    python-magic \
    einops

RUN pip install num2words==0.5.12 dateparser==1.1.8
RUN pip install transformers==4.39.3

# ===== Install UniDic =====
RUN pip install --no-cache-dir unidic \
    && python3 -m unidic download \
    && rm -rf /usr/local/lib/python3.10/site-packages/unidic/dicdir \
    && ln -s /root/.local/share/unidic /usr/local/lib/python3.10/site-packages/unidic/dicdir

RUN pip uninstall -y unidic_lite || true

# ===== Install MeloTTS =====
RUN git clone https://github.com/myshell-ai/MeloTTS.git /app/MeloTTS \
    && pip install --no-deps -e /app/MeloTTS

# ===== OpenVoice =====
RUN git clone https://github.com/myshell-ai/OpenVoice.git /app/OpenVoice \
    && pip install --no-build-isolation --no-deps -e /app/OpenVoice

COPY . /app

WORKDIR /app/Dstonylion

ENTRYPOINT ["../config/scripts/entrypoint.prod.sh"]
