version: "3"
services:
  web:
    container_name: web
    image: stonylion_backend:latest
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      DJANGO_SETTINGS_MODULE: Dstonylion.stonylion.settings
    env_file:
      - .env
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    expose:
      - 8000
    entrypoint:
      - sh
      - /app/config/docker/entrypoint.prod.sh
    working_dir: /app/Dstonylion

  asgi:
    container_name: asgi
    image: stonylion_backend:latest
    command: daphne -b 0.0.0.0 -p 8001 stonylion.asgi:application
    working_dir: /app/Dstonylion
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: Dstonylion.stonylion.settings
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    expose:
      - 8001
    depends_on:
      - web

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      TZ: "Asia/Seoul"

volumes:
  static:
  media:
