services:
  web:
    container_name: web
    image: stonylion_backend:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    expose:
      - 8000
    working_dir: /app/Dstonylion
    entrypoint:
      - sh
      - /app/config/docker/entrypoint.prod.sh
    environment:
      DJANGO_SETTINGS_MODULE: stonylion.settings

  asgi:
    container_name: asgi
    image: stonylion_backend:latest
    working_dir: /app/Dstonylion
    command: daphne -b 0.0.0.0 -p 8001 stonylion.asgi:application
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: stonylion.settings
    depends_on:
      - web
    volumes:
      - static:/app/staticfiles
      - media:/app/media

  nginx:
    container_name: nginx
    build: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static:/app/staticfiles
      - media:/app/media

volumes:
  static:
  media:
