services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn stonylion.wsgi:application -b 0.0.0.0:8000 --workers 3 --threads 2 --timeout 600 --log-level debug --error-logfile - --capture-output
    env_file:
      - .env
    volumes:
      - static:/app/staticfiles
      - media:/app/media
      - /home/ubuntu/MeloTTS:/app/MeloTTS
      - /home/ubuntu/OpenVoice:/app/OpenVoice
      - /home/ubuntu/models:/app/models
      - outputs_v2:/app/Dstonylion/outputs_v2
    ports:
      - "8000:8000"
    working_dir: /app/Dstonylion
    entrypoint:
      - sh
      - /app/config/docker/entrypoint.prod.sh
    environment:
      DJANGO_SETTINGS_MODULE: stonylion.settings

  asgi:
    container_name: asgi
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app/Dstonylion
    entrypoint:
      - sh
      - /app/config/docker/entrypoint.asgi.sh
    command: daphne -b 0.0.0.0 -p 8001 stonylion.asgi:application
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: stonylion.settings
    depends_on:
      - web
    volumes:
      - static:/app/staticfiles
      - media:/app/media
      - /home/ubuntu/MeloTTS:/app/MeloTTS
      - /home/ubuntu/OpenVoice:/app/OpenVoice
      - /home/ubuntu/models:/app/models
      - outputs_v2:/app/Dstonylion/outputs_v2

  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - asgi
    volumes:
      - static:/app/staticfiles
      - media:/app/media

volumes:
  static:
  media:
  outputs_v2:
