# Generated by Django 5.2.7 on 2025-11-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mylibrary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="likes",
        ),
        migrations.DeleteModel(
            name="History",
        ),
    ]
