# Generated by Django 5.2.7 on 2025-11-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylibrary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="last_viewed_page",
            field=models.IntegerField(default=0),
        ),
    ]
