# Generated by Django 5.2.8 on 2025-11-14 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '0001_initial'),
        ('story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='story.story'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='illustrationjob',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='story.story'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AI.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='story.story'),
        ),
        migrations.AddField(
            model_name='storyextension',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extensions', to='story.story'),
        ),
        migrations.AddField(
            model_name='storyextension',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extensions', to=settings.AUTH_USER_MODEL),
        ),
    ]
