# Generated by Django 5.2.8 on 2025-11-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_illustrationjob_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllustrationJobPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_status', to='AI.illustrationjob')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
