# Generated by Django 5.2.7 on 2025-11-08 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0003_remove_storyextension_prompt_and_more"),
        ("story", "0002_alter_story_child_alter_story_voice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="story",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatrooms",
                to="story.story",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("user", "User"), ("ai", "AI")], default=1, max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_chatrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="prompt",
            field=models.TextField(blank=True),
        ),
    ]
