# Generated by Django 5.2.7 on 2025-11-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0004_rename_timestamp_chatroom_created_at_chatroom_story_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
