# Generated by Django 5.2.8 on 2025-11-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_illustrationjobpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustrationjob',
            name='job_type',
            field=models.CharField(choices=[('full', '전체 생성'), ('regen', '페이지 재생성')], default='full', max_length=10),
        ),
    ]
