# Generated by Django 5.2.8 on 2025-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0006_extendchat_extendmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendchat",
            name="user_token_count",
            field=models.IntegerField(default=0),
        ),
    ]
