# Generated by Django 5.2.8 on 2025-11-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0005_illustrationjob_job_type"),
        ("AI", "0006_extendchat_is_continuing"),
    ]

    operations = []
