# Generated by Django 5.2.8 on 2025-11-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0007_merge_20251125_1558"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="illustrationjob",
            name="job_type",
        ),
        migrations.DeleteModel(
            name="IllustrationJobPage",
        ),
    ]
