# Generated by Django 5.2.8 on 2025-11-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0007_extendchat_user_token_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendchat",
            name="is_continuing",
            field=models.BooleanField(default=False),
        ),
    ]
