# Generated by Django 5.2.8 on 2025-11-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0008_remove_illustrationjob_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="illustrationjob",
            name="job_type",
            field=models.CharField(
                choices=[("full", "전체 생성"), ("regen", "페이지 재생성")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="IllustrationJobPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_status",
                        to="AI.illustrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
    ]
