# Generated by Django 5.2.7 on 2025-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='children/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_file',
            field=models.FileField(upload_to='voices/'),
        ),
    ]
