# Generated by Django 5.2.7 on 2025-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child_profile_image_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='language',
            field=models.CharField(default='ko', max_length=10),
        ),
    ]
