# Generated by Django 5.2.8 on 2025-11-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_birth_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_code',
            field=models.CharField(blank=True, default='woman', max_length=50, null=True),
        ),
    ]
