# Generated by Django 5.2.8 on 2025-11-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clonedvoice',
            name='voice_profile_image',
        ),
        migrations.AddField(
            model_name='clonedvoice',
            name='voice_image_code',
            field=models.CharField(default='child1', max_length=50),
        ),
    ]
