# Generated by Django 5.2.7 on 2025-11-06 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_voice_emotion_voice_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='emotion',
        ),
        migrations.AddField(
            model_name='voice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
