# Generated by Django 5.2.8 on 2025-11-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_clonedvoice_voice_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='child',
            name='child_image_code',
            field=models.CharField(default='child1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clonedvoice',
            name='voice_image_code',
            field=models.CharField(max_length=50),
        ),
    ]
