# Generated by Django 5.2.7 on 2025-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_voice_emotion_voice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='voices/profiles/'),
        ),
    ]
