# Generated by Django 5.2.8 on 2025-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_child_profile_image_child_child_image_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clonedvoice',
            name='voice_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
