# Generated by Django 5.2.8 on 2025-11-12 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_voice_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='user',
        ),
        migrations.CreateModel(
            name='ClonedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_file', models.FileField(blank=True, null=True, upload_to='cloned_se/')),
                ('cloned_voice_file', models.FileField(blank=True, null=True, upload_to='tts_outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_voices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
