# Generated by Django 5.2.8 on 2025-11-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_voice_user_clonedvoice'),
        ('story', '0002_alter_story_voice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
