# Generated by Django 5.2.8 on 2025-11-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='clonedvoice',
            name='voice_name',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
