# Generated by Django 5.2.8 on 2025-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clonedvoice_voice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clonedvoice',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clonedvoice',
            name='voice_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
