# Generated by Django 5.2.8 on 2025-11-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clonedvoice_file_url_clonedvoice_voice_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clonedvoice',
            old_name='file_url',
            new_name='reference_audio_url',
        ),
    ]
