# Generated by Django 5.2.8 on 2025-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_file_url_clonedvoice_reference_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
