# Generated by Django 5.2.8 on 2025-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_child_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
